### PR TITLE
fix(rn-camera): remove lodash dependency

### LINKED ISSUE #1993: remove lodash dependency
# Feature-Request

**Describe the Feature**
Remove `lodash` as a dependency. No need to pull in the whole library.

**Possible Implementations**
We can use `Object.entries(props).map()` instead. 

**Related Issues**
NONE

> Love react-native-camera? Please consider supporting our collective: 👉  https://opencollective.com/react-native-camera/donate
> Want this feature to be resolved faster? Please consider adding a bounty to it https://issuehunt.io/repos/33218414

### PR DESCRIPTION
**Pull request by n1ru4l**
Closes #1993

### CODE REVIEW

File: src/RNCamera.js [hunk 1]
```diff
@@ -461,7 +468,7 @@ export default class Camera extends React.Component<PropsType, StateType> {
     }
   }
 
-  _convertNativeProps(props: PropsType) {
+  _convertNativeProps({ children, ...props }: PropsType) {
```
Comment (n1ru4l) [inline src/RNCamera.js]: @sibelius I excluded `children` from the props here? Will this result in a performance improvement? IDK if the children would be passed to the native instance as a string or something like that

Comment (sibelius) [reply src/RNCamera.js]: Not sure either

Comment (n1ru4l) [reply src/RNCamera.js]: I mean it wont hurt not passing it because it is not intended to be passed down 😉
