### PR TITLE
fix(android): use device orientation for images/videos instead of display orientation

### LINKED ISSUE #1053: Orientation of captured photo wrong
I implemented camera like in documentation.
If I take photo with camera and phone is landscape (lock button up) image orientation is good.
But if I do the same with lock button down image is turned upside down.
On android work fine this issue is on IOS.

Does anybody have any idea how to fix this?

UPDATE

If I add fixOrientation to true it fix issue and orientation is good but I see that this function is deprecated.
Even the portrait taken photos are landscape when show them in browser.
Why I need to call this function to get good orientation if in documentation it says that it is not needed any more? What could be the reason I am getting all photos in landscape.

### LINKED ISSUE #1725: RNCamera Android Orientation
So, RNCamera on Android will frequently save pictures in the wrong orientation. This seems to happen especially when the app's orientation has been locked - in my case, my app is locked to landscape orientation, and pictures will be saved correctly in one orientation, and upside down in the other orientation.

I'm very much not an expert on this, but I've been digging through the code and other posted issues, and near as I can tell this happens because RNCamera is finding its orientation by listening for onOrientationChanged events. (I don't know if locking the orientation blocks these events from firing or what, but like I said, very much not an expert)

The fixOrientation option seems to take the final image, read its real exif orientation, then processes the image to match that, I think? The big problem is that it's slow as hell, especially compared to RCTCamera.

So I figured I'd check in case I've missed a solution or workaround somewhere - has anybody figured out how to fix this, or come up with a workaround that doesn't multiply the amount of time it takes to take a picture?

If not, I _think_ I may have found where the camera orientation change happens. Please correct me if I'm wrong: The RNCameraView implements Google's CameraView, and just straight up calls super.takePicture(). CameraView seems to be a very nice and neat and convenient wrapper around the Camera API, so that's nice, except it bases its orientation on listening for onOrientationChanged events.

So, in theory, adding a check for the device's real orientation to CameraView's takePicture() function might solve the orientation issue without needing to reprocess every single picture.

EDIT: Yeah, I was mostly wrong, slightly right. CameraView uses yet another wrapper around the Camera API, and that's where the API is really called. Camera1.java takePictureInternal(). Finally, something I recognize from the old version.

Heading to lunch now, but I'm gonna try that after. Figured I'd put this up. Am I on totally the wrong path here? Has anybody solved this, so I don't have to waste time being wrong or duplicating someone else's solution?

### PR DESCRIPTION
**Pull request by n1ru4l**
This is my attempt for fixing #1725 based on the work of @Fsarmento (https://github.com/react-native-community/react-native-camera/issues/1725#issuecomment-441599916 https://github.com/react-native-community/react-native-camera/compare/master...Fsarmento:master)

This PR unifies the orientation used for the pictures/video with the `ios` implementation by using the device orientation instead of the display orientation.

**Related:**

Fixes #1725
Closes #1941
Fixes #1053

cc @sibelius @JulienUsson @SimonErm @Tsiniloiv

Could you please test this implementation? I tested all orientations (including when device is locked in portrait mode). But before merging I want at least one more person to test the implementation.

### CODE REVIEW

**Comment by sibelius** [comment]
why do we need 3 variables to handle orientation?

**Comment by n1ru4l** [comment]
@sibelius 

- `mScreenOrientation` is needed for correctly rendering the `CameraScene`(using `mDisplayOrientation` could distort/traverse the camera output visible to the user.

- `mDeviceOrientation` is used for getting the orientation of the video/image if `mOrientation` does not override it.

- `mOrientation` is set by the user if he passes the `orientation` option to `recordAsync`/`takePictureAsync` and overrides the orientation which would otherwise determined by `mDeviceOrientation`.

**Comment by JulienMalige** [comment]
@n1ru4l I'm from the @JulienUsson's team.

On this branch, on **iOS**, I still have an issue. When I take a picture in **portrait**:
```
deviceOrientation:1  // OK
pictureOrientation:1 // OK
```
but my exif looks wrong (reversed):
```
...
PixelXDimension:4032
PixelYDimension:1864
...
```
When I save it to the Library, the orientation is wrong (portrait in landscape, landscape in portrait).

**Comment by n1ru4l** [comment]
@FSarmento @matheuscorreia Would be awesome if you could also test the implementation

**Comment by matheuscorreia** [comment]
Tested this on a Samsung SM-G930F (Android 8.0.0), and it presented some odd behaviours. These tests were made on picture mode only.

Back camera at 0° - Worked;
Back camera at 90° - Worked;
Back camera at 180° - Worked;
Back camera at 270° - Worked;

Front camera at 0° - Worked;
Front camera at 90° - Did not work; Picture turned out upside down;
Front camera at 180° - Worked;
Front camera at 270° - Did not work; Picture turned out upside down;

File: android/src/main/java/com/google/android/cameraview/Camera1.java [hunk 1]
```diff
@@ -706,12 +718,12 @@ private int calcDisplayOrientation(int screenOrientationDegrees) {
...
      */
     private int calcCameraRotation(int screenOrientationDegrees) {
-        if (mCameraInfo.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
-            return (mCameraInfo.orientation + screenOrientationDegrees) % 360;
-        } else {  // back-facing
-            final int landscapeFlip = isLandscape(screenOrientationDegrees) ? 180 : 0;
-            return (mCameraInfo.orientation + screenOrientationDegrees + landscapeFlip) % 360;
-        }
+       if (mCameraInfo.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) {
+           return (mCameraInfo.orientation + screenOrientationDegrees) % 360;
```
Comment (sibelius) [inline android/src/main/java/com/google/android/cameraview/Camera1.java]: ?why front facing camera does not need landspaceFlip/

Comment (n1ru4l) [reply android/src/main/java/com/google/android/cameraview/Camera1.java]: Idk why but changing only applying it to the front facing instead of the back facing fixes this issue 🤣 At least on my Nexus 5X...

**Comment by n1ru4l** [comment]
@matheuscorreia Could you please try again 😊

**Comment by matheuscorreia** [comment]
Working perfectly now, @n1ru4l. Good job on this PR!

LGTM \o/

**Comment by sibelius** [comment]
@n1ru4l great job on this

we've tested and it is working great

🚀

**Comment by n1ru4l** [comment]
@Fsarmento did most of the work. Thank you :fire:

**Comment by jgcmarins** [comment]
what is missing for merge?

**Comment by Fsarmento** [comment]
You're welcome @n1ru4l, great work!

**Comment by n1ru4l** [comment]
@Fsarmento I am totally for also adding `displayOrientation` to the possible options, maybe we should name it `useDisplayOrientation` do be more explicit?
