### PR TITLE
fix(picture-size): create None default value

### LINKED ISSUE #1613: RNCamera: Front Camera shows black screen in example app on iOS
While ttrying testing (and fixing the feature #1606) with the rn-camera-example application ( https://github.com/react-native-community/rncamera-example). I discovered the following problems:

**Steps to reproduce:**

1. Clone `rn-camera-example` at the current master (https://github.com/react-native-community/rncamera-example/commit/4f87d52fe41be0bb85eb57b7e7f1456e2f7cdc5f)

```bash
git clone https://github.com/react-native-community/rncamera-example.git
cd rncamera-example
# checkout commit in which this occures (master at time of the posting)
git checkout 4f87d52fe41be0bb85eb57b7e7f1456e2f7cdc5f
```

2. Install `react-native-camera` at the version before #1606 got merged

```bash
yarn add react-native-camera@https://github.com/react-native-community/react-native-camera.git#9cddb2a7213697663f6e53ad8c9603cd11c16754
```

3. Open xcode project and run App on device.

4. Use the toggle button to switch between cameras.

**Observation:**

- **The Front Camera only shows a black screen (sometimes the app crashes while switching)**
- **After the RNCamera Component shows a black screen pressing the SNAP button results in  ~~an application crash~~ a thrown exception**

```error
ExceptionsManager.js:73 Exception thrown while executing UI block: *** -[AVCaptureStillImageOutput captureStillImageAsynchronouslyFromConnection:completionHandler:] Inactive/invalid connection passed
```

**Investigation:**

When I install the following version of react-native-camera (4a9322cb8b7d455fc28f7e67a15bff2fd9d7ea3e) aka the commit before the preview feature was implemented:

```bash
yarn add react-native-camera@https://github.com/react-native-community/react-native-camera.git#4a9322cb8b7d455fc28f7e67a15bff2fd9d7ea3e
```

The app crashes upon start (with `EXC_BAD_ACCESS `)

Poor mans console output 😢:
```
2018-06-06 23:40:02.768087+0200 RNCameraExample[1240:505681] Instantiated <GMVFaceDetector: 0x1740917b0>
2018-06-06 23:40:02.798836+0200 RNCameraExample[1240:505681] Instantiated <GMVFaceDetector: 0x1702817c0>
(lldb)
```

After applying the following patch everything seems to be fine:

```diff
diff --git a/App.js b/App.js
index 47b560d..8440591 100644
--- a/App.js
+++ b/App.js
@@ -192,9 +192,9 @@ export default class CameraScreen extends React.Component {
         zoom={this.state.zoom}
         whiteBalance={this.state.whiteBalance}
         ratio={this.state.ratio}
-        faceDetectionLandmarks={RNCamera.Constants.FaceDetection.Landmarks.all}
-        onFacesDetected={this.onFacesDetected}
-        onFaceDetectionError={this.onFaceDetectionError}
+        // faceDetectionLandmarks={RNCamera.Constants.FaceDetection.Landmarks.all}
+        // onFacesDetected={this.onFacesDetected}
+        // onFaceDetectionError={this.onFaceDetectionError}
         focusDepth={this.state.depth}
         permissionDialogTitle={'Permission to use camera'}
         permissionDialogMessage={'We need your permission to use your camera phone'}
```

It seems like there a two different problems:

1. **The preview feature somehow breaked using the front camera**
2. **Using the face detection results in a bad access crash**

### PR DESCRIPTION
**Pull request by jgfidelis**
fix front camera problems reported on #1613

Closes #1613

### CODE REVIEW

File: android/src/main/java/org/reactnative/camera/RNCameraView.java [hunk 1]
```diff
@@ -127,30 +127,38 @@ public void onFramePreview(CameraView cameraView, byte[] data, int width, int he
         int correctWidth = width;
         int correctHeight = height;
         byte[] correctData = data;
+        boolean willCallBarCodeTask = mShouldScanBarCodes && !barCodeScannerTaskLock && cameraView instanceof BarCodeScannerAsyncTaskDelegate;
+        boolean willCallFaceTask = mShouldDetectFaces && !faceDetectorTaskLock && cameraView instanceof FaceDetectorAsyncTaskDelegate;
+        boolean willCallGoogleBarcodeTask = mShouldGoogleDetectBarcodes && !googleBarcodeDetectorTaskLock && cameraView instanceof BarcodeDetectorAsyncTaskDelegate;
+        boolean willCallTextTask = mShouldRecognizeText && !textRecognizerTaskLock && cameraView instanceof TextRecognizerAsyncTaskDelegate;
+        if (!willCallBarCodeTask && !willCallFaceTask && !willCallGoogleBarcodeTask && !willCallTextTask) {
```
Comment (jgfidelis) [inline android/src/main/java/org/reactnative/camera/RNCameraView.java]: prevent unnecessary rotation on `onFramePreview`

**Comment by n1ru4l** [comment]
For the future we all should test the code of pull requests before merging it 😅

Any way to automate this (since it requires a real device) 🤔

**Comment by sibelius** [comment]
Can we automate this using detox?
